### ISSUE TITLE
[Warlock] Pets get summoned in-between legs.

### ISSUE THREAD

**Issue by Tixlenra** [azerothcore/azerothcore-classic#18]
**Description of the Issue:**
Pets get summoned in-between legs.

**What should happen:**
They should spawn on your left side, facing your orientation.

**How to reproduce:**
Summon a pet.

**Video Proof:** Coming Later

**Comment by talamortis** [comment]
Fixed 
https://github.com/talamortis/azerothcore-classic/commit/5ce11943a67ebc4a4c95ff38c52cfeee828666cf
