### ISSUE TITLE
[Warlock] No Summon Stun when Summoning a New Pet (UNCONFIRMED, IGNORE PLEASE)

### ISSUE THREAD

**Issue by Tixlenra** [azerothcore/azerothcore-classic#21]
**Description of the Issue:**
When you have a pet out and try to summon a new one, usually, from memory, the warlock is stunned (UNCONFIRMED FOR THIS PATCH, PLEASE IGNORE FOR NOW, IF IT TURNS OUT THIS IS FALSE I WILL DELETE AT A LATER TIME)

**What should happen:**
The pet currently summoned should be stunned for the entire duration of the summon.

**How to reproduce:**
Summon a pet with one already active.

CANNOT remember or FIND PROOF of the stun being in 1.12.1. Will continue to research when I have time.

**Comment by talamortis** [comment]
Warlocks did not stun the pet in this patch the spell it uses is 
https://www.burning-crusade.com/database/?spell=32752

which wasn't implemented in 1.12.1

**Comment by Tixlenra** [comment]
Thanks for confirming.
