### ISSUE TITLE
[Engineering] Masterwork Target Dummy

### ISSUE THREAD

**Issue by Tixlenra** [azerothcore/azerothcore-classic#5]
Currently: Attacks enemies and follows you around when there's no one left. Does not taunt properly.

Should be: stood still, not attacking, the taunt should taunt all around him; the initial taunt spell lasts for 3 seconds.

Source: http://db.vanillagaming.org/?item=16023#wh-comments

**Comment by talamortis** [comment]
Fixed https://github.com/azerothcore/ScriptDev3/commit/0e3507011b910d8d217ce118ed39912d7c376fd1
